// export type Database = {
//   public: {
//     Tables: {
//       users: {
//         Row: {
//           id: string
//           full_name: string
//           email: string
//           mobile_number: string
//           state: string
//           city: string
//           created_at: string
//           last_login: string | null
//           is_verified: boolean
//         }
//         Insert: {
//           id?: string
//           full_name: string
//           email: string
//           mobile_number: string
//           state: string
//           city: string
//           created_at?: string
//           last_login?: string | null
//           is_verified?: boolean
//         }
//         Update: {
//           id?: string
//           full_name?: string
//           email?: string
//           mobile_number?: string
//           state?: string
//           city?: string
//           created_at?: string
//           last_login?: string | null
//           is_verified?: boolean
//         }
//       }
//     }
//   }
// }

// In lib/supabase/database.types.ts

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          full_name: string
          email: string
          mobile_number: string
          state: string
          city: string
          created_at: string
          last_login: string | null
          is_verified: boolean
        }
        Insert: {
          id?: string
          full_name: string
          email: string
          mobile_number: string
          state: string
          city: string
          created_at?: string
          last_login?: string | null
          is_verified?: boolean
        }
        Update: {
          id?: string
          full_name?: string
          email?: string
          mobile_number?: string
          state?: string
          city?: string
          created_at?: string
          last_login?: string | null
          is_verified?: boolean
        }
      },
      otps: {
        Row: {
          id: string
          mobile_number: string
          otp_code: string
          expires_at: string // Use string for TIMESTAMPTZ
          attempts: number
          created_at: string // Use string for TIMESTAMPTZ
        }
        Insert: {
          id?: string
          mobile_number: string
          otp_code: string
          expires_at: string // Use string for TIMESTAMPTZ
          attempts?: number
          created_at?: string // Use string for TIMESTAMPTZ
        }
        Update: {
          id?: string
          mobile_number?: string
          otp_code?: string
          expires_at?: string // Use string for TIMESTAMPTZ
          attempts?: number
          created_at?: string // Use string for TIMESTAMPTZ
        }
      }
    }
    // Add Functions, Enums, etc. if you have them
    Functions: {}
    Enums: {}
  }
}

// Helper types if needed (usually generated by Supabase CLI)
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]